# Generated by Django 5.2.10 on 2026-02-08 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_auth', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='refreshtoken',
            name='location',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
