# Generated by Django 5.2.10 on 2026-02-08 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='auth0_connection',
        ),
        migrations.RemoveField(
            model_name='user',
            name='auth0_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_synced_at',
        ),
        migrations.AddField(
            model_name='user',
            name='auth_provider',
            field=models.CharField(default='magic_link', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
