# Generated by Django 5.2.10 on 2026-02-08 16:20

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_auth0_connection_remove_user_auth0_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.ImageField(blank=True, default='', upload_to=apps.users.models.profile_picture_path),
        ),
    ]
